name: CI Build

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - add-ci-build  # Triggers on push to the `add-ci-build` branch
  pull_request:
    branches:
      - main  # Triggers when a pull request is created targeting the `main` branch
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run linting with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests
        env:
          DATABASE_URI: "postgresql://postgres:pgs3cr3t@postgres:5432/testdb"

        
